name: Add issue to project

on:
  workflow_call:
    inputs:
      project:
        description: 'ID of the project in the Camunda organization to add the issue to'
        required: true
        type: string

jobs:
  Exec:
    permissions:
      id-token: write  # mint GitHub OIDC token for Vault JWT auth
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc  # v4.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          role: ${{ secrets.VAULT_JWT_ROLE }}
          path: ${{ secrets.VAULT_JWT_PATH }}
          jwtGithubAudience: ${{ secrets.VAULT_JWT_AUDIENCE }}
          exportEnv: false
          secrets: |
            secret/data/products/cambpm/ci/github-workflow GITHUB_APP_ID;
            secret/data/products/cambpm/ci/github-workflow GITHUB_APP_PRIVATE_KEY;
      - name: Generate token for GitHub
        id: generate-github-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ steps.secrets.outputs.GITHUB_APP_ID }}
          private_key: ${{ steps.secrets.outputs.GITHUB_APP_PRIVATE_KEY }}
      - name: Add to project
        uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85
        with:
          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/${{ inputs.project }}
          github-token: ${{ steps.generate-github-token.outputs.token }}
