name: Backport merged pull request
on:
  workflow_call:
    inputs:
      ref:
        description: 'The reference of the github commit of the reusable workflow. Must match the specified branch/tag/commit where the workflow is called. Workaround to https://github.com/actions/runner/issues/2417. Should never be untrusted content.'
        default: 'main'
        type: string
    secrets:
      VAULT_ADDR:
        required: true
      VAULT_ROLE_ID:
        required: true
      VAULT_SECRET_ID:
        required: true
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
  actions: write
jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Only run when pull request is merged
    # or when a comment containing `/backport` is created
    if: >
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '/backport')
      )
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/cambpm/ci/github-workflow GITHUB_APP_ID;
            secret/data/products/cambpm/ci/github-workflow GITHUB_APP_PRIVATE_KEY;
      - name: Generate token for GitHub
        id: generate-github-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ steps.secrets.outputs.GITHUB_APP_ID }}
          private_key: ${{ steps.secrets.outputs.GITHUB_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-github-token.outputs.token }}
      - name: Create backport pull requests
        uses: tasso94/backport-action@main
        with:
          github_token: ${{ steps.generate-github-token.outputs.token }}
          experimental: |- 
            { "downstream_repo": "${{ github.event.repository.name }}-maintenance"}
          pull_description:  |-
            # Description
            Backport of ${{ github.repository_owner }}/${{ github.event.repository.name }}#${pull_number} to `${target_branch}`.
          branch_name: ${target_branch}-backport-${pull_number}
          copy_assignees: true
          copy_requested_reviewers: true
          label_pattern: ^bot:backport:([^ ]+)$
          copy_labels_pattern: ^ci:([^ ]+)$
