name: "Test: Send SUPPORT and SEC notifications"

on: 
  workflow_dispatch:
    inputs:
      versions:
        description: 'Release versions (comma-separated list, e.g. 7.17.0,7.16.3,7.15.8)'
        required: true


jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/extract-issue-links.yml@main    
    secrets: inherit
    with: 
      versions: ${{ github.event.inputs.versions }}
      support-webhook-secret: TEST_CHANNEL_SLACK_WEBHOOK_URL
      sec-webhook-secret: TEST_CHANNEL_SLACK_WEBHOOK_URL
      translation-webhook-secret: TEST_CHANNEL_SLACK_WEBHOOK_URL
      translation-notification-matcher: 1\.[0-9]+\.3
      devex-webhook-secret: TEST_CHANNEL_SLACK_WEBHOOK_URL
      devex-notification-matcher: 2\.[0-9]+\.4
      sec-dri-secret: SEC_DRI_SLACK_ID
