name: Set Version Labels

on:
  issues:
    types:
      - closed

jobs:
  version-label-automation:
    runs-on: ubuntu-latest
    name: version-label-automation
    steps:
      - name: version-label-automation-step
        id: version-label-automation-step
        uses: camunda/automation-platform-github-actions/version-label-automation@main
        with: 
          issue-number: ${{ github.event.issue.number }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
