name: Set Version Labels

on:
  workflow_call:

jobs:
  version-label-automation:
    runs-on: ubuntu-latest
    name: version-label-automation
    steps:
      - name: version-label-automation-step
        id: version-label-automation-step
        uses: camunda/automation-platform-github-actions/version-label-automation@main
        with: 
          assignee: ${{ github.event.issue.assignee }}
          assignees: ${{ github.event.issue.assignees }}
          issue-number: ${{ github.event.issue.number }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
